[package]
name = "fourier-prof"
version = "0.1.0"
authors = ["Caleb Zulawski <caleb.zulawski@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
clap = "2.33"
fourier = { path = "../fourier" }
num-complex = "0.3"
rand = "0.7"
