[package]
name = "fourier-ffi"
version = "0.1.0"
authors = ["Caleb Zulawski <caleb.zulawski@gmail.com>"]
edition = "2018"
publish = false

[lib]
name = "fourier"
crate_type = ["cdylib", "staticlib"]
doc = false

[dependencies]
fourier = { path = "../fourier" }
libc = "0.2"
num-complex = "0.3"
