[package]
name = "fourier"
version = "0.1.0"
authors = ["Caleb Zulawski <caleb.zulawski@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Fast Fourier transforms (FFTs)"
repository = "https://github.com/calebzulawski/fourier"
categories = ["algorithms", "mathematics", "multimedia::audio", "science"]
readme = "README.md"
edition = "2018"

[dependencies]
num-traits = "0.2"
num-complex = "0.2"
multiversion = "0.3"

[dev-dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
num-complex = { version = "0.2", features = ["serde"] }
float-cmp = "0.6"
